"""
LangGraph state definition for V4 orchestrator
"""
from typing import TypedDict, List, Dict, Any, Optional


class AuditState(TypedDict):
    """State schema for URL audit workflow"""
    
    # Current URL being audited
    url: str
    
    # Raw page context from crawler
    page_context: Dict[str, Any]
    
    # Column headers to audit
    column_headers: List[str]
    
    # Current column being processed
    current_column: Optional[str]
    
    # Intermediate variables (reusable across columns)
    # Example: {"page_html": "<html>...", "title_text": "My Page"}
    intermediate_vars: Dict[str, Any]
    
    # Primitive execution plans per column
    # {column_name: {operations: [...], final_result_template: {...}}}
    execution_plans: Dict[str, Dict[str, Any]]
    
    # Raw metric results per column
    # {column_name: {metric1: value1, metric2: value2, ...}}
    raw_metrics: Dict[str, Dict[str, Any]]
    
    # Final summaries per column (generated by writer agent)
    # {column_name: "Professional SEO summary text..."}
    summaries: Dict[str, str]
    
    # Global FAISS query results (for duplication checks)
    faiss_results: Dict[str, Any]
    
    # Current node in workflow
    current_node: str
    
    # Error tracking
    errors: List[str]